spring:
  application:
    name: eos-admin-client
server:
  port: 2008
eureka:
  client:
    service-url:
       defaultZone : http://localhost:8761/eureka/

provider:
  ribbon :
    ConnectTimeout : 600
    ReadTimeout : 6000
    OkToRetryOnAllOperations : true
    MaxAutoRetriesNextServer : 2
    MaxAutoRetries : 1


feign:
  hystrix:
    enabled: true

hystrix :
  command :
    holle3 :
      execution :
        isolation :
          thread :
            timeoutInMilliseconds : 10000