spring:
  cloud:
    config:
      discovery:
        enabled: true
  application:
    name: eos-admin-server
  rabbitmq:
    host: 192.168.0.201
    port: 5672
    username: root
    password: root
  datasource:
    password: ${jdbc.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ${jdbc.url}
    username: ${jdbc.userName}
server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
mybatis:
  configuration:
    lazy-loading-enabled: true
    aggressive-lazy-loading: false
    cache-enabled: true
    local-cache-scope: session
    default-executor-type: reuse
    auto-mapping-behavior: partial
    multiple-result-sets-enabled: true
    use-column-label: true
    jdbc-type-for-null: null
    map-underscore-to-camel-case: true
    use-generated-keys: true
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.duohao.wallet.eosadminserver.model
jdbc:
  password: 123456
  userName: root
  url: jdbc:mysql://127.0.0.1:3306/20170406?characterEncoding=utf8&serverTimezone=UTC

env : envwwwwwdddd发郭德纲的说法
